
server:
  port: 8081
  servlet:
    # 应用的访问路径
    context-path: /
    tomcat:
      # tomcat的URI编码
      uri-encoding: UTF-8
      # tomcat最大线程数，默认为200
      max-threads: 256
      # Tomcat启动初始化的线程数，默认值25
      min-spare-threads: 16

netty:
  heartbeat-timeout: 60000

websocket:
  port: 7777

tcpserver:
  port: 9000

spring:
  profiles:
    active: @profileActive@

logging:
  level:
    com.ruoyi: debug
    org.springframework: warn